
package apkkasir;

import dao.DAO_Produk;
import java.util.List;
import javax.swing.JOptionPane;
import model.model_Produk;
import service.service_Produk;
import tableModel.tableMod_Produk;


public class FormBarang extends javax.swing.JPanel {

    private service_Produk servis = new DAO_Produk();
    private tableMod_Produk tblModel = new tableMod_Produk();
    
    public FormBarang() {
        initComponents();
        
        tbl_Produk.setModel(tblModel);
        
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        mainPanel = new javax.swing.JPanel();
        dataBarang = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Produk = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        bt_Tambah = new javax.swing.JButton();
        bt_Hapus = new javax.swing.JButton();
        bt_Batal = new javax.swing.JButton();
        text_Cari = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tambahBarang = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bt_Simpan = new javax.swing.JButton();
        bt_Batal2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        text_IdProduk = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        text_NamaProduk = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        text_HargaBeli = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        text_HargaJual = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        text_Stok = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        combo_Satuan = new javax.swing.JComboBox<>();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        dataBarang.setBackground(new java.awt.Color(255, 255, 255));

        tbl_Produk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_Produk.setSelectionBackground(new java.awt.Color(255, 255, 255));
        tbl_Produk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_ProdukMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_Produk);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Data Produk");

        bt_Tambah.setText("TAMBAH");
        bt_Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_TambahActionPerformed(evt);
            }
        });

        bt_Hapus.setText("HAPUS");
        bt_Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_HapusActionPerformed(evt);
            }
        });

        bt_Batal.setText("BATAL");
        bt_Batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_BatalActionPerformed(evt);
            }
        });

        text_Cari.setText("Cari Produk Disini");
        text_Cari.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        text_Cari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                text_CariMouseClicked(evt);
            }
        });
        text_Cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text_CariKeyTyped(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-search-24.png"))); // NOI18N

        javax.swing.GroupLayout dataBarangLayout = new javax.swing.GroupLayout(dataBarang);
        dataBarang.setLayout(dataBarangLayout);
        dataBarangLayout.setHorizontalGroup(
            dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 832, Short.MAX_VALUE)
            .addGroup(dataBarangLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataBarangLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(674, Short.MAX_VALUE))
                    .addGroup(dataBarangLayout.createSequentialGroup()
                        .addComponent(bt_Tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_Hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_Batal, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(text_Cari, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(28, 28, 28))))
        );
        dataBarangLayout.setVerticalGroup(
            dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bt_Tambah)
                        .addComponent(bt_Hapus)
                        .addComponent(bt_Batal)
                        .addComponent(text_Cari, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE))
        );

        mainPanel.add(dataBarang, "card2");

        tambahBarang.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Tambah Produk");

        bt_Simpan.setText("SIMPAN");
        bt_Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_SimpanActionPerformed(evt);
            }
        });

        bt_Batal2.setText("BATAL");
        bt_Batal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_Batal2ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("ID Produk");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Nama Produk");

        text_NamaProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_NamaProdukActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Harga Beli");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Harga Jual");

        text_HargaJual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_HargaJualActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Satuan");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Stok");

        combo_Satuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Jenis Satuan -", "Pcs", "Kg", "Pack", "Dus", "Renceng" }));
        combo_Satuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_SatuanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(text_HargaJual)
                    .addComponent(text_NamaProduk, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text_IdProduk, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(text_HargaBeli, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text_Stok, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combo_Satuan, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(text_IdProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(text_NamaProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(text_HargaBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(text_HargaJual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(text_Stok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(combo_Satuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tambahBarangLayout = new javax.swing.GroupLayout(tambahBarang);
        tambahBarang.setLayout(tambahBarangLayout);
        tambahBarangLayout.setHorizontalGroup(
            tambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahBarangLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(tambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(tambahBarangLayout.createSequentialGroup()
                        .addComponent(bt_Simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_Batal2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(565, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tambahBarangLayout.setVerticalGroup(
            tambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tambahBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Simpan)
                    .addComponent(bt_Batal2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(tambahBarang, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void bt_TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_TambahActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(tambahBarang);
        mainPanel.repaint();
        mainPanel.revalidate();
        
        bt_Simpan.setText("SIMPAN");
        text_IdProduk.setText(servis.nomor());
        
        if(bt_Tambah.getText().equals("UBAH"))
        {
            dataTabel();
        }
    }//GEN-LAST:event_bt_TambahActionPerformed

    private void bt_SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_SimpanActionPerformed
        if(bt_Simpan.getText().equals("TAMBAH"))
        {
            bt_Simpan.setText("SIMPAN");
            text_IdProduk.setText(servis.nomor());
        }
        else if(bt_Simpan.getText().equals("SIMPAN"))
        {
            simpanData();
        }
        else if(bt_Simpan.getText().equals("PERBARUI"))
        {
            perbaruiData();
        }
    }//GEN-LAST:event_bt_SimpanActionPerformed

    private void bt_Batal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_Batal2ActionPerformed
        tampilPanel();
        loadData();
        resetForm();
//        mainPanel.removeAll();
//        mainPanel.add(dataBarang);
//        mainPanel.repaint();
//        mainPanel.revalidate();
    }//GEN-LAST:event_bt_Batal2ActionPerformed

    private void combo_SatuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_SatuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_SatuanActionPerformed

    private void text_NamaProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_NamaProdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_NamaProdukActionPerformed

    private void text_HargaJualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_HargaJualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_HargaJualActionPerformed

    private void tbl_ProdukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_ProdukMouseClicked
        if(bt_Tambah.getText().equals("TAMBAH"))
        {
            bt_Tambah.setText("UBAH");
        }
        bt_Hapus.setVisible(true);
        bt_Batal.setVisible(true);
    }//GEN-LAST:event_tbl_ProdukMouseClicked

    private void bt_HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_HapusActionPerformed
        hapusData();
    }//GEN-LAST:event_bt_HapusActionPerformed

    private void bt_BatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_BatalActionPerformed
        tampilPanel();
        loadData();
    }//GEN-LAST:event_bt_BatalActionPerformed

    private void text_CariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_CariMouseClicked
        text_Cari.setText("");
    }//GEN-LAST:event_text_CariMouseClicked

    private void text_CariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_CariKeyTyped
        pencarian();
    }//GEN-LAST:event_text_CariKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Batal;
    private javax.swing.JButton bt_Batal2;
    private javax.swing.JButton bt_Hapus;
    private javax.swing.JButton bt_Simpan;
    private javax.swing.JButton bt_Tambah;
    private javax.swing.JComboBox<String> combo_Satuan;
    private javax.swing.JPanel dataBarang;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel tambahBarang;
    private javax.swing.JTable tbl_Produk;
    private javax.swing.JTextField text_Cari;
    private javax.swing.JTextField text_HargaBeli;
    private javax.swing.JTextField text_HargaJual;
    private javax.swing.JTextField text_IdProduk;
    private javax.swing.JTextField text_NamaProduk;
    private javax.swing.JTextField text_Stok;
    // End of variables declaration//GEN-END:variables
    private void dataTabel(){
        dataBarang.setVisible(false);
        tambahBarang.setVisible(true);
        
        int row = tbl_Produk.getSelectedRow();
        jLabel2.setText("Perbarui Data Produk");
        
        text_IdProduk.setEnabled(false);
        
        text_IdProduk.setText       (tbl_Produk.getModel().getValueAt(row, 0).toString());
        text_NamaProduk.setText     (tbl_Produk.getModel().getValueAt(row, 1).toString());
        text_HargaBeli.setText      (tbl_Produk.getModel().getValueAt(row, 2).toString());
        text_HargaJual.setText      (tbl_Produk.getModel().getValueAt(row, 3).toString());
        text_Stok.setText           (tbl_Produk.getModel().getValueAt(row, 4).toString());
        combo_Satuan.setSelectedItem(tbl_Produk.getModel().getValueAt(row, 5).toString());
        
        aktif();
        bt_Simpan.setText("PERBARUI");
        bt_Batal.setVisible(true);
    }
    private void aktif(){
        text_NamaProduk.setEnabled(true);
        text_HargaBeli.setEnabled(true);
        text_HargaJual.setEnabled(true);
        text_Stok.setEnabled(true);
        combo_Satuan.setEnabled(true);
        
    }
    private void loadData() {
        bt_Hapus.setVisible(false);
        bt_Batal.setVisible(false);
        List<model_Produk> list = servis.getData();
        tblModel.setData(list);
    }
    private void hapusData(){
        int index = tbl_Produk.getSelectedRow();
        if (index!=-1) {
            model_Produk brg = tblModel.getData(tbl_Produk.convertRowIndexToModel(index));
            if (JOptionPane.showConfirmDialog(null, "Yakin data akan di hapus?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION)== JOptionPane.OK_OPTION) {
                servis.hapusData(brg);
                tblModel.hapusData(index);
                loadData();
                resetForm();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Pilih dahulu record yang akan di update");
        }
    }

    private void simpanData() {
        if(validasiInput()==true){
            int id_produk         = Integer.parseInt(text_IdProduk.getText());
            String nama_produk    = text_NamaProduk.getText();
            Long harga_beli       = Long.parseLong(text_HargaBeli.getText());
            Long harga_jual       = Long.parseLong(text_HargaJual.getText());
            int stok              = Integer.parseInt(text_Stok.getText());
            String satuan         = combo_Satuan.getSelectedItem().toString();
            
            model_Produk brg = new model_Produk();
            
            brg.setId_produk(id_produk);
            brg.setNama_produk(nama_produk);
            brg.setHarga_beli(harga_beli);
            brg.setHarga_jual(harga_jual);
            brg.setStok(stok);
            brg.setSatuan(satuan);
            
            servis.tambahData(brg);
            tblModel.tambahData(brg);
            loadData();
            resetForm();
            tampilPanel();
            bt_Simpan.setText("TAMBAH");
        }
    }

    private void perbaruiData() {
        int index = tbl_Produk.getSelectedRow();
        if (index!=-1) {
            model_Produk mobar = tblModel.getData(tbl_Produk.convertRowIndexToModel(index));
            
            if(validasiInput()==true){
                int id_produk = Integer.parseInt(text_IdProduk.getText());
                String nama_produk    = text_NamaProduk.getText();
                Long harga_beli       = Long.parseLong(text_HargaBeli.getText());
                Long harga_jual       = Long.parseLong(text_HargaJual.getText());
                int stok              = Integer.parseInt(text_Stok.getText());
                String satuan         = combo_Satuan.getSelectedItem().toString();
                
                model_Produk brg = new model_Produk();
                
                brg.setId_produk(id_produk);
                brg.setNama_produk(nama_produk);
                brg.setHarga_beli(harga_beli);
                brg.setHarga_jual(harga_jual);
                brg.setStok(stok);
                brg.setSatuan(satuan);
                
                servis.perbaruiData(brg);
                tblModel.perbaruiData(index, brg);
                loadData();
                resetForm();
                tampilPanel();
            }
        }
        
    }

    private void resetForm() {
        bt_Tambah.requestFocus();
        bt_Tambah.setText("TAMBAH");
        text_IdProduk.setText("");
        text_NamaProduk.setText("");
        text_HargaBeli.setText("");
        text_HargaJual.setText("");
        text_Stok.setText("");
        combo_Satuan.setSelectedItem(0);
    }

    private void tampilPanel() {
        mainPanel.removeAll();
        mainPanel.add(new FormBarang());
        mainPanel.repaint();
        mainPanel.revalidate();
    }

    private boolean validasiInput() {
        boolean valid = false;
        if (text_IdProduk.getText().trim().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Id produk tidak boleh kosong");
        }else if (text_NamaProduk.getText().trim().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Nama produk tidak boleh kosong");
        }else if (text_HargaBeli.getText().trim().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Harga Beli tidak boleh kosong");
        }else if (text_HargaJual.getText().trim().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Harga Jual tidak boleh kosong");
        }else if (text_Stok.getText().trim().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Stok produk tidak boleh kosong");
        }else if (combo_Satuan.getSelectedItem().equals(null) ){
            JOptionPane.showMessageDialog(null, "Satuan produk tidak boleh kosong");
        }else{
            valid = true;
        }
        return valid;
    }

    private void pencarian() {
        List<model_Produk> list = servis.pencarian2(text_Cari.getText());
        tblModel.setData(list);
    }
        
}
