
package apkkasir;

import dao.DAO_User;
import java.util.List;
import javax.swing.JOptionPane;
import model.model_User;
import service.service_User;
import tableModel.tableModel_User;


public class FormUser extends javax.swing.JPanel {

    private service_User servis = new DAO_User();
    private tableModel_User tblModel = new tableModel_User();
    
    public FormUser() {
        initComponents();
        
        tbl_User.setModel(tblModel);
        
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        mainPanel = new javax.swing.JPanel();
        dataUser = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_User = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        bt_Tambah = new javax.swing.JButton();
        bt_Hapus = new javax.swing.JButton();
        bt_Batal = new javax.swing.JButton();
        text_Cari = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tambahUser = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bt_Simpan = new javax.swing.JButton();
        bt_Batal2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        text_IdUser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        text_NamaUser = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        text_Email = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        text_Telepon = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        text_Username = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        combo_Role = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        text_Pass = new javax.swing.JPasswordField();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        dataUser.setBackground(new java.awt.Color(255, 255, 255));

        tbl_User.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_User.setSelectionBackground(new java.awt.Color(255, 255, 255));
        tbl_User.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_UserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_User);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Data User");

        bt_Tambah.setText("TAMBAH");
        bt_Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_TambahActionPerformed(evt);
            }
        });

        bt_Hapus.setText("HAPUS");
        bt_Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_HapusActionPerformed(evt);
            }
        });

        bt_Batal.setText("BATAL");
        bt_Batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_BatalActionPerformed(evt);
            }
        });

        text_Cari.setText("Cari User Disini");
        text_Cari.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        text_Cari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                text_CariMouseClicked(evt);
            }
        });
        text_Cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text_CariKeyTyped(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-search-24.png"))); // NOI18N

        javax.swing.GroupLayout dataUserLayout = new javax.swing.GroupLayout(dataUser);
        dataUser.setLayout(dataUserLayout);
        dataUserLayout.setHorizontalGroup(
            dataUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 832, Short.MAX_VALUE)
            .addGroup(dataUserLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(dataUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataUserLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(706, Short.MAX_VALUE))
                    .addGroup(dataUserLayout.createSequentialGroup()
                        .addComponent(bt_Tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_Hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_Batal, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(text_Cari, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(28, 28, 28))))
        );
        dataUserLayout.setVerticalGroup(
            dataUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dataUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(dataUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bt_Tambah)
                        .addComponent(bt_Hapus)
                        .addComponent(bt_Batal)
                        .addComponent(text_Cari, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE))
        );

        mainPanel.add(dataUser, "card2");

        tambahUser.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Tambah User");

        bt_Simpan.setText("SIMPAN");
        bt_Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_SimpanActionPerformed(evt);
            }
        });

        bt_Batal2.setText("BATAL");
        bt_Batal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_Batal2ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("ID User ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Nama");

        text_NamaUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_NamaUserActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Email");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("No Telepon");

        text_Telepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_TeleponActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Password");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Username");

        combo_Role.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        combo_Role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Role -", "ADMIN", "KASIR", "OWNER", " " }));
        combo_Role.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_RoleActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Role");

        text_Pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_PassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text_Telepon, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(text_NamaUser)
                    .addComponent(text_IdUser)
                    .addComponent(text_Email)
                    .addComponent(text_Username)
                    .addComponent(combo_Role, 0, 756, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(text_Pass))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(text_IdUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(text_NamaUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(text_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(text_Telepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(text_Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(12, 12, 12)
                .addComponent(text_Pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(combo_Role, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tambahUserLayout = new javax.swing.GroupLayout(tambahUser);
        tambahUser.setLayout(tambahUserLayout);
        tambahUserLayout.setHorizontalGroup(
            tambahUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahUserLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(tambahUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(tambahUserLayout.createSequentialGroup()
                        .addComponent(bt_Simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_Batal2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(565, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tambahUserLayout.setVerticalGroup(
            tambahUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tambahUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tambahUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Simpan)
                    .addComponent(bt_Batal2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(tambahUser, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void bt_TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_TambahActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        mainPanel.add(tambahUser);
        mainPanel.repaint();
        mainPanel.revalidate();
        
        bt_Simpan.setText("SIMPAN");
        text_IdUser.setText(servis.nomor());
        
        if(bt_Tambah.getText().equals("UBAH"))
        {
            dataTabel();
        }
    }//GEN-LAST:event_bt_TambahActionPerformed

    private void bt_SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_SimpanActionPerformed
        if(bt_Simpan.getText().equals("TAMBAH"))
        {
            bt_Simpan.setText("SIMPAN");
            text_IdUser.setText(servis.nomor());
        }
        else if(bt_Simpan.getText().equals("SIMPAN"))
        {
            simpanData();
        }
        else if(bt_Simpan.getText().equals("PERBARUI"))
        {
            perbaruiData();
        }
    }//GEN-LAST:event_bt_SimpanActionPerformed

    private void bt_Batal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_Batal2ActionPerformed
        tampilPanel();
        loadData();
        resetForm();
//        mainPanel.removeAll();
//        mainPanel.add(dataBarang);
//        mainPanel.repaint();
//        mainPanel.revalidate();
    }//GEN-LAST:event_bt_Batal2ActionPerformed

    private void combo_RoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_RoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_RoleActionPerformed

    private void text_NamaUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_NamaUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_NamaUserActionPerformed

    private void text_TeleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_TeleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_TeleponActionPerformed

    private void tbl_UserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_UserMouseClicked
        if(bt_Tambah.getText().equals("TAMBAH"))
        {
            bt_Tambah.setText("UBAH");
        }
        bt_Hapus.setVisible(true);
        bt_Batal.setVisible(true);
    }//GEN-LAST:event_tbl_UserMouseClicked

    private void bt_HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_HapusActionPerformed
        hapusData();
    }//GEN-LAST:event_bt_HapusActionPerformed

    private void bt_BatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_BatalActionPerformed
        tampilPanel();
        loadData();
    }//GEN-LAST:event_bt_BatalActionPerformed

    private void text_CariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_CariMouseClicked
        text_Cari.setText("");
    }//GEN-LAST:event_text_CariMouseClicked

    private void text_CariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_CariKeyTyped
        pencarian();
    }//GEN-LAST:event_text_CariKeyTyped

    private void text_PassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_PassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_PassActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Batal;
    private javax.swing.JButton bt_Batal2;
    private javax.swing.JButton bt_Hapus;
    private javax.swing.JButton bt_Simpan;
    private javax.swing.JButton bt_Tambah;
    private javax.swing.JComboBox<String> combo_Role;
    private javax.swing.JPanel dataUser;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel tambahUser;
    private javax.swing.JTable tbl_User;
    private javax.swing.JTextField text_Cari;
    private javax.swing.JTextField text_Email;
    private javax.swing.JTextField text_IdUser;
    private javax.swing.JTextField text_NamaUser;
    private javax.swing.JPasswordField text_Pass;
    private javax.swing.JTextField text_Telepon;
    private javax.swing.JTextField text_Username;
    // End of variables declaration//GEN-END:variables
    private void dataTabel(){
        dataUser.setVisible(false);
        tambahUser.setVisible(true);
        
        int row = tbl_User.getSelectedRow();
        jLabel2.setText("Perbarui Data User");
        
        text_IdUser.setEnabled(false);
        
        text_IdUser.setText         (tbl_User.getModel().getValueAt(row, 1).toString());
        text_NamaUser.setText       (tbl_User.getModel().getValueAt(row, 2).toString());
        text_Email.setText          (tbl_User.getModel().getValueAt(row, 3).toString());
        text_Telepon.setText        (tbl_User.getModel().getValueAt(row, 4).toString());
        text_Username.setText       (tbl_User.getModel().getValueAt(row, 5).toString());
        text_Pass.setText           (tbl_User.getModel().getValueAt(row, 6).toString());
        combo_Role.setSelectedItem  (tbl_User.getModel().getValueAt(row, 7).toString());
        
        aktif();
        bt_Simpan.setText("PERBARUI");
        bt_Batal.setVisible(true);
    }
    private void aktif(){
        text_NamaUser.setEnabled(true);
        text_Email.setEnabled(true);
        text_Telepon.setEnabled(true);
        text_Username.setEnabled(true);
        text_Pass.setEnabled(true);
        combo_Role.setEnabled(true);
        
    }
    private void loadData() {
        bt_Hapus.setVisible(false);
        bt_Batal.setVisible(false);
        List<model_User> list = servis.getData();
        tblModel.setData(list);
    }
    private void hapusData(){
        int index = tbl_User.getSelectedRow();
        if (index!=-1) {
            model_User brg = tblModel.getData(tbl_User.convertRowIndexToModel(index));
            if (JOptionPane.showConfirmDialog(null, "Yakin data akan di hapus?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION)== JOptionPane.OK_OPTION) {
                servis.hapusData(brg);
                tblModel.hapusData(index);
                loadData();
                resetForm();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Pilih dahulu record yang akan di update");
        }
    }

    private void simpanData() {
        if(validasiInput()==true){
            int id_user           = Integer.parseInt(text_IdUser.getText());
            String nama_user      = text_NamaUser.getText();
            String email          = text_Email.getText();
            int no                = Integer.parseInt(text_Telepon.getText());
            String username       = text_Username.getText();
            String pass           = text_Pass.getText();
            String role           = combo_Role.getSelectedItem().toString();
            
            model_User brg = new model_User();
            
            brg.setId_pengguna(id_user);
            brg.setFullname(nama_user);
            brg.setEmail(email);
            brg.setTelepon(no);
            brg.setUsernama(username);
            brg.setPass(pass);
            brg.setRole(role);
            
            servis.tambahData(brg);
            tblModel.tambahData(brg);
            loadData();
            resetForm();
            tampilPanel();
            bt_Simpan.setText("TAMBAH");
        }
    }

    private void perbaruiData() {
        int index = tbl_User.getSelectedRow();
        if (index!=-1) {
            model_User mod_user = tblModel.getData(tbl_User.convertRowIndexToModel(index));
            
            if(validasiInput()==true){
                int id_user           = Integer.parseInt(text_IdUser.getText());
                String nama_user      = text_NamaUser.getText();
                String email          = text_Email.getText();
                int no                = Integer.parseInt(text_Telepon.getText());
                String username       = text_Username.getText();
                String pass           = text_Pass.getText();
                String role           = combo_Role.getSelectedItem().toString();
            
                model_User brg = new model_User();
            
                brg.setId_pengguna(id_user);
                brg.setFullname(nama_user);
                brg.setEmail(email);
                brg.setTelepon(no);
                brg.setUsernama(username);
                brg.setPass(pass);
                brg.setRole(role);
                
                servis.perbaruiData(brg);
                tblModel.perbaruiData(index, brg);
                loadData();
                resetForm();
                tampilPanel();
            }
        }
        
    }

    private void resetForm() {
        bt_Tambah.requestFocus();
        bt_Tambah.setText("TAMBAH");
        text_IdUser.setText("");
        text_NamaUser.setText("");
        text_Email.setText("");
        text_Telepon.setText("");
        text_Username.setText("");
        text_Pass.setText("");
        combo_Role.setSelectedItem(0);
    }

    private void tampilPanel() {
        mainPanel.removeAll();
        mainPanel.add(new FormUser());
        mainPanel.repaint();
        mainPanel.revalidate();
    }

    private boolean validasiInput() {
        boolean valid = false;
        if (text_IdUser.getText().trim().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Id User tidak boleh kosong");
        }else if (text_NamaUser.getText().trim().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Nama tidak boleh kosong");
        }else if (text_Email.getText().trim().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Email tidak boleh kosong");
        }else if (text_Telepon.getText().trim().isEmpty() ){
            JOptionPane.showMessageDialog(null, "No Telepon tidak boleh kosong");
        }else if (text_Username.getText().trim().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Username tidak boleh kosong");
        }else if (text_Pass.getText().trim().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Password tidak boleh kosong");
        }else if (combo_Role.getSelectedItem().equals(null) ){
            JOptionPane.showMessageDialog(null, "Role produk tidak boleh kosong");
        }else{
            valid = true;
        }
        return valid;
    }

    private void pencarian() {
        List<model_User> list = servis.pencarian(text_Cari.getText());
        tblModel.setData(list);
    }
        
}
