/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package apkkasir;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public class formProfilKasir extends javax.swing.JPanel {

    private String id; 
    private String name;
    private String email;
    private String phone;
    private String role;
    
    public formProfilKasir(String id, String name, String email, String phone, String role) {
        initComponents();
        this.id = id;
        this.name = name;
        this.email = email;
        this.phone = phone;
        this.role = role;
        
        idUserText.setText(String.valueOf(id));
        idUserText.setEditable(false);  // Membuat text field tidak bisa diubah
        namaText.setText(name);
        namaText.setEditable(false);
        emailText.setText(email);
        emailText.setEditable(false);
        tlpText.setText(String.valueOf(phone));
        tlpText.setEditable(false);
        roleText.setText(role);
        roleText.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        namalb = new javax.swing.JLabel();
        idUserlb = new javax.swing.JLabel();
        emaillb = new javax.swing.JLabel();
        tlplb = new javax.swing.JLabel();
        rolelb = new javax.swing.JLabel();
        idUserText = new javax.swing.JTextField();
        namaText = new javax.swing.JTextField();
        emailText = new javax.swing.JTextField();
        tlpText = new javax.swing.JTextField();
        roleText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        namalb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        namalb.setText("NAMA");

        idUserlb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        idUserlb.setText("ID USER");

        emaillb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        emaillb.setText("ALAMAT EMAIL");

        tlplb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tlplb.setText("TELEPON");

        rolelb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rolelb.setText("ROLE");

        idUserText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idUserTextActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user (1).png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Profil");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(roleText, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tlpText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                        .addComponent(emailText, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(namaText, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(rolelb, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(emaillb, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(idUserlb, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(namalb, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tlplb, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(idUserText, javax.swing.GroupLayout.Alignment.LEADING))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(idUserlb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(idUserText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(namalb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(namaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(emaillb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tlplb))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tlpText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rolelb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(roleText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void idUserTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idUserTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idUserTextActionPerformed
    public void getProfile(int userId) {
        try (Connection conn = databasekoneksi.getConnection()) {
            String query = "SELECT id_user, fullname, email, role, username, password FROM user WHERE id_user =?";
            PreparedStatement stmt = conn.prepareStatement(query);
            stmt.setInt(1, userId);

            ResultSet rs = stmt.executeQuery();
            if (rs.next()) {
                idUserText.setText(rs.getString("id_user"));
                namaText.setText(rs.getString("fullname"));
                emailText.setText(rs.getString("email"));
                roleText.setText(rs.getString("role"));
//                usernameText.setText(rs.getString("username"));
//                passwordText.setText(rs.getString("password")); 
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailText;
    private javax.swing.JLabel emaillb;
    private javax.swing.JTextField idUserText;
    private javax.swing.JLabel idUserlb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField namaText;
    private javax.swing.JLabel namalb;
    private javax.swing.JTextField roleText;
    private javax.swing.JLabel rolelb;
    private javax.swing.JTextField tlpText;
    private javax.swing.JLabel tlplb;
    // End of variables declaration//GEN-END:variables
}
