
package apkkasir;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.Timer;


public class Menu_Utama extends javax.swing.JFrame {
    private Timer timer;


    public Menu_Utama(String nama, String level, String mail, String tlp, String id) {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        lb_nama.setText(nama);
        lb_level.setText(level);
        lb_email.setText(mail);
        lb_phone.setText(tlp);
        lb_id.setText(id);
        execute(level);
        Date();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_navbar = new javax.swing.JPanel();
        lb_tanggal = new javax.swing.JLabel();
        lb_tanggal1 = new javax.swing.JLabel();
        panel_sidebar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pn_menu = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lb_level = new javax.swing.JLabel();
        lb_nama = new javax.swing.JLabel();
        lb_phone = new javax.swing.JLabel();
        lb_email = new javax.swing.JLabel();
        lb_id = new javax.swing.JLabel();
        panel_content = new javax.swing.JPanel();
        panel_utama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panel_navbar.setBackground(new java.awt.Color(0, 204, 204));
        panel_navbar.setPreferredSize(new java.awt.Dimension(1000, 120));

        lb_tanggal.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lb_tanggal.setForeground(new java.awt.Color(255, 255, 255));
        lb_tanggal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_tanggal.setText("Tanggal & Waktu");

        lb_tanggal1.setFont(new java.awt.Font("Clarendon Blk BT", 1, 24)); // NOI18N
        lb_tanggal1.setForeground(new java.awt.Color(255, 255, 255));
        lb_tanggal1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_tanggal1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kasir/icon/Logo.png"))); // NOI18N
        lb_tanggal1.setText("Bram Mart");

        javax.swing.GroupLayout panel_navbarLayout = new javax.swing.GroupLayout(panel_navbar);
        panel_navbar.setLayout(panel_navbarLayout);
        panel_navbarLayout.setHorizontalGroup(
            panel_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_navbarLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lb_tanggal1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 518, Short.MAX_VALUE)
                .addComponent(lb_tanggal)
                .addContainerGap())
        );
        panel_navbarLayout.setVerticalGroup(
            panel_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_navbarLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(panel_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_navbarLayout.createSequentialGroup()
                        .addComponent(lb_tanggal)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_navbarLayout.createSequentialGroup()
                        .addComponent(lb_tanggal1)
                        .addGap(28, 28, 28))))
        );

        getContentPane().add(panel_navbar, java.awt.BorderLayout.PAGE_START);

        panel_sidebar.setBackground(new java.awt.Color(0, 204, 204));
        panel_sidebar.setPreferredSize(new java.awt.Dimension(300, 500));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        pn_menu.setBackground(new java.awt.Color(0, 204, 204));
        pn_menu.setLayout(new javax.swing.BoxLayout(pn_menu, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(pn_menu);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        lb_level.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lb_level.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_level.setText("Level");
        lb_level.setPreferredSize(new java.awt.Dimension(56, 30));

        lb_nama.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lb_nama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_nama.setText("Nama");
        lb_nama.setPreferredSize(new java.awt.Dimension(56, 30));

        lb_phone.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lb_phone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_phone.setText("Nama");
        lb_phone.setPreferredSize(new java.awt.Dimension(56, 30));

        lb_email.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lb_email.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_email.setText("Nama");
        lb_email.setPreferredSize(new java.awt.Dimension(56, 30));

        lb_id.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lb_id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_id.setText("Nama");
        lb_id.setPreferredSize(new java.awt.Dimension(56, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lb_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(lb_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lb_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(lb_level, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(lb_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(174, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(lb_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_email, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lb_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_level, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(lb_id, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(111, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout panel_sidebarLayout = new javax.swing.GroupLayout(panel_sidebar);
        panel_sidebar.setLayout(panel_sidebarLayout);
        panel_sidebarLayout.setHorizontalGroup(
            panel_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_sidebarLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel_sidebarLayout.setVerticalGroup(
            panel_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_sidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(panel_sidebar, java.awt.BorderLayout.LINE_START);

        panel_content.setBackground(new java.awt.Color(204, 204, 204));
        panel_content.setPreferredSize(new java.awt.Dimension(635, 550));

        panel_utama.setBackground(new java.awt.Color(255, 255, 255));
        panel_utama.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout panel_contentLayout = new javax.swing.GroupLayout(panel_content);
        panel_content.setLayout(panel_contentLayout);
        panel_contentLayout.setHorizontalGroup(
            panel_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_contentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_utama, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_contentLayout.setVerticalGroup(
            panel_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_contentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_utama, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(panel_content, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(891, 747));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        panel_utama.add(new content_bg());
        panel_utama.repaint();
        panel_utama.revalidate();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        String nama = null;
        String level = null;
        String tlp = null;
        String mail = null;
        String id = null;
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FromLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_email;
    private javax.swing.JLabel lb_id;
    private javax.swing.JLabel lb_level;
    private javax.swing.JLabel lb_nama;
    private javax.swing.JLabel lb_phone;
    private javax.swing.JLabel lb_tanggal;
    private javax.swing.JLabel lb_tanggal1;
    private javax.swing.JPanel panel_content;
    private javax.swing.JPanel panel_navbar;
    private javax.swing.JPanel panel_sidebar;
    private javax.swing.JPanel panel_utama;
    private javax.swing.JPanel pn_menu;
    // End of variables declaration//GEN-END:variables

    private void execute(String level) {
        ImageIcon iconMaster   = new ImageIcon(getClass().getResource("/img/mas_Home.png"));
        ImageIcon iconUser     = new ImageIcon(getClass().getResource("/img/mas_User.png"));
        ImageIcon iconProduk   = new ImageIcon(getClass().getResource("/img/mas_Produk.png"));
        ImageIcon iconTransaksi   = new ImageIcon(getClass().getResource("/img/mas_Transaksi.png"));
        ImageIcon iconRiwayat   = new ImageIcon(getClass().getResource("/img/mas_Riwayat.png"));
        ImageIcon iconLogout   = new ImageIcon(getClass().getResource("/img/mas_Logout.png"));
        ImageIcon iconProfil   = new ImageIcon(getClass().getResource("/img/mas_Profil.png"));
        
//        MenuItem masBarang      = new MenuItem(null, true, iconBarang, "Barang", null);
//        MenuItem masBarang2     = new MenuItem(null, true, iconBarang, "Barang2", null);
//        MenuItem masBarang3     = new MenuItem(null, true, iconBarang, "Barang3", null);
//        
//        MenuItem masTransaksi     = new MenuItem(null, true, iconBarang, "Transaksi", null);
//        MenuItem masTransaksi2    = new MenuItem(null, true, iconBarang, "Transaksi2", null);
//        MenuItem masTransaksi3    = new MenuItem(null, true, iconBarang, "Transaksi3", null);
        
//        MenuItem menuMaster    = new MenuItem(iconMaster, false, null, "Master", null, masBarang, masBarang2, masBarang3);
//        MenuItem menuTransaksi = new MenuItem(iconMaster, false, null, "Transaksi", null, masTransaksi, masTransaksi2, masTransaksi3);
        MenuItem menuHome    = new MenuItem(iconMaster, false, null, "Dashboard", (ActionEvent e) -> {
            panel_utama.removeAll();
            panel_utama.add(new MasterDashboard());
            panel_utama.repaint();
            panel_utama.revalidate();
        });
        MenuItem menuUser    = new MenuItem(iconUser, false, null, "Data User", (ActionEvent e) -> {
            panel_utama.removeAll();
            panel_utama.add(new FormUser());
            panel_utama.repaint();
            panel_utama.revalidate();
        });
        MenuItem menuProduk  = new MenuItem(iconProduk, false, null, "Data Produk", (ActionEvent e) -> {
            panel_utama.removeAll();
            panel_utama.add(new FormBarang());
            panel_utama.repaint();
            panel_utama.revalidate();
        });
        MenuItem menuTransaksi    = new MenuItem(iconTransaksi, false, null, "Transaksi", (ActionEvent e) -> {
            String id = lb_id.getText();
            String name = lb_nama.getText();
            panel_utama.removeAll();
            panel_utama.add(new FormPenjualan(id, name)); // Kirimkan `model_User` ke `FormPenjualan`
            panel_utama.repaint();
            panel_utama.revalidate();
        });
        MenuItem menuProfil  = new MenuItem(iconProfil, false, null, "Profil", (ActionEvent e) -> {
            String id = lb_id.getText();
            String name = lb_nama.getText();
            String email = lb_email.getText();
            String phone = lb_phone.getText();
            String role = lb_level.getText();
            panel_utama.removeAll();
            panel_utama.add(new formProfilKasir(id, name, email, phone, role));
            panel_utama.repaint();
            panel_utama.revalidate();
        });
        MenuItem menuRiwayat = new MenuItem(iconRiwayat, false, null, "Riwayat Transaksi", null);
        MenuItem menuLaporan = new MenuItem(iconRiwayat, false, null, "Laporan Transaksi", (ActionEvent e) -> {
            panel_utama.removeAll();
            panel_utama.add(new formlaporan());
            panel_utama.repaint();
            panel_utama.revalidate();
        });
        MenuItem menuLaporanKasir = new MenuItem(iconRiwayat, false, null, "Laporan Transaksi Kasir", (ActionEvent e) -> {
            panel_utama.removeAll();
            panel_utama.add(new formlaporanPenjualanKasir());
            panel_utama.repaint();
            panel_utama.revalidate();
        });
        MenuItem menuLogout = new MenuItem(iconLogout, false, null, "Log Out", (ActionEvent e) -> {
            String name = lb_nama.getText();
            String role = lb_level.getText();
            this.setVisible(false);
                FromLogin h = new FromLogin();
                h.setVisible(true);
                h.revalidate();
                
                dispose();
                fungsi.savelog("" + name + " , sebagai " + role + " telah log out ");
        });
        
        if(level.equals("KASIR")){
            addMenu (menuTransaksi, menuLaporan, menuProfil, menuLogout);
        }else if(level.equals("OWNER")){
            addMenu (menuHome, menuLaporan, menuLaporanKasir, menuLogout);
        }else{
            addMenu (menuHome, menuUser, menuProduk, menuTransaksi, menuLaporan, menuLaporanKasir, menuProfil, menuLogout);
        }
                
    }
    
    private void addMenu(MenuItem... menu) {
        for (MenuItem menu1 : menu) {
            pn_menu.add(menu1);
            ArrayList<MenuItem> subMenu = menu1.getSubMenu();
            for (MenuItem m : subMenu) {
                addMenu(m);
            }
        }
        pn_menu.revalidate();
    }

    private void Date() {
        timer = new Timer(1000, new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                Calendar calender = Calendar.getInstance();
                Date now = new Date();
                SimpleDateFormat formatHari = new SimpleDateFormat("EEEE", new Locale("in","ID"));
                SimpleDateFormat formatTanggal  = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
                String hari = formatHari.format(calender.getTime());
                String waktuTanggal = formatTanggal.format(now);
                lb_tanggal.setText(hari+", "+waktuTanggal);
            }
        });
        
        timer.start();
    }
    
}
